[font]
size = 12
[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"
# family = "JetBrainsMono Nerd Font"
# style = "Bold"
[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
# family = "JetBrainsMono Nerd Font"
# style = "Regular"
# [font.italic]
# family = "JetBrainsMono Nerd Font"
# style = "Italic"
# [font.bold_italic]
# family = "JetBrainsMono Nerd Font"
# style = "Bold Italic"

[window]
# startup_mode = "Fullscreen"
# startup_mode: "Maximized"
decorations = "None"
opacity = 0.9
[window.dimensions]
columns = 200
lines = 45

# Colors (Dracula)
# Default colors
[colors.normal]
black = "#000000"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"
# Normal colors
[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"
# Bright colors
[colors.bright]
black = "#575b70"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"
