# OhMyZsh related things
export ZSH="$HOME/.oh-my-zsh"

## updates frequency
export UPDATE_ZSH_DAYS=14

ZSH_THEME="dracula"

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)
bindkey '^ ' autosuggest-accept

source $ZSH/oh-my-zsh.sh


# User configuration
## aliases
alias v="nvim"
alias c='xclip -selection clipboard'
alias gco="git br | fzf | xargs git co"
alias grm="git br | fzf | xargs git br -D"

## add directories to $PATH
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.pyenv/bin"
export PATH="$PATH:/usr/local/go/bin"

# init pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

## setup for time utility
export TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'

## setting for tmuxp
export DISABLE_AUTO_TITLE='true'

## setup for fzf utility
export FZF_DEFAULT_OPTS='--color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

