BASH_PLUGINS="$HOME/.config/bash_plugins"
source "$BASH_PLUGINS/startup.sh"

export ZSH="$HOME/.oh-my-zsh"
## updates frequency
export UPDATE_ZSH_DAYS=14

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)
bindkey '^ ' autosuggest-accept

source "$ZSH/oh-my-zsh.sh"

source "$BASH_PLUGINS/aliases.sh"
source "$BASH_PLUGINS/functions.sh"
source "$BASH_PLUGINS/exports.sh"
source "$BASH_PLUGINS/finalize.sh"
