export ZSH="$HOME/.oh-my-zsh"
## updates frequency
export UPDATE_ZSH_DAYS=14

ZSH_THEME="robbyrussell"

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)
bindkey '^ ' autosuggest-accept

source "$ZSH/oh-my-zsh.sh"

BASH_PLUGINS="$HOME/.config/bash_plugins"
source "$BASH_PLUGINS/aliases.sh"
source "$BASH_PLUGINS/doc.sh"
source "$BASH_PLUGINS/qcd.sh"
source "$BASH_PLUGINS/exports.sh"
